### ISSUE TITLE
Error during start cpp file

### ISSUE THREAD

**Issue by furkank75** [BIGBALLON/tensorflow_tricks#3]
Hi, 
i became the following error:
```
./classifier 
Using TensorFlow backend.
Can't find Module
Traceback (most recent call last):
  File "./vgg_model.py", line 4, in <module>
    import keras
  File "/usr/local/lib/python3.5/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
ImportError: No module named 'tensorflow'

```

Tensorflow and Keras are installed! The script vgg_model.py are works successfull and get me the prediction!! How can I solve this??

**Comment by BIGBALLON** [comment]
@furkank75 Is TF installed correctly?

```
/usr/local/lib/python3.5/dist-packages.....
```

make sure your TensorFlow / Keras path is right, I think you need double-check it.

**Comment by furkank75** [comment]
Ok, I solve this Problem. Thanks a lot. Can I used this only also with CPU?

**Comment by BIGBALLON** [comment]
@furkank75 of course, simply checkout your tf to CPU mode.
